<a href="https://colab.research.google.com/github/sreelakshmithilakan/E-Commerce-Customer-Intelligence-and-Sales-Analytics/blob/main/Sales_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [102]:
import pandas as pd
import numpy as np

In [103]:
#Load customers orders and payments

customers = pd.read_csv('olist_customers_dataset.csv')
orders = pd.read_csv('olist_orders_dataset.csv')
payments = pd.read_csv('olist_order_payments_dataset.csv')

print("All datasets loaded successfully!")

All datasets loaded successfully!

Check data

In [104]:
print(customers.shape)
print(orders.shape)
print(payments.shape)

(99441, 5)
(99441, 8)
(103886, 5)

In [105]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [106]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,02-10-2017 10:56,02-10-2017 11:07,04-10-2017 19:55,10-10-2017 21:25,18-10-2017 00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,24-07-2018 20:41,26-07-2018 03:24,26-07-2018 14:31,07-08-2018 15:27,13-08-2018 00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,08-08-2018 08:38,08-08-2018 08:55,08-08-2018 13:50,17-08-2018 18:06,04-09-2018 00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,18-11-2017 19:28,18-11-2017 19:45,22-11-2017 13:39,02-12-2017 00:28,15-12-2017 00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,13-02-2018 21:18,13-02-2018 22:20,14-02-2018 19:46,16-02-2018 18:17,26-02-2018 00:00

In [107]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [108]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [109]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [110]:
payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [111]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [112]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [113]:
payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [114]:
#convert into date time

orders['order_purchase_timestamp'] = pd.to_datetime(
    orders['order_purchase_timestamp'],
    dayfirst=True
)

In [115]:
orders['order_purchase_timestamp']

0       2017-10-02 10:56:00
1       2018-07-24 20:41:00
2       2018-08-08 08:38:00
3       2017-11-18 19:28:00
4       2018-02-13 21:18:00
                ...
99436   2017-03-09 09:54:00
99437   2018-02-06 12:58:00
99438   2017-08-27 14:46:00
99439   2018-01-08 21:28:00
99440   2018-03-08 20:57:00
Name: order_purchase_timestamp, Length: 99441, dtype: datetime64[ns]

In [116]:
orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [117]:
orders = orders[
    orders['order_status'] == 'delivered'
]

In [118]:
orders['order_status'].value_counts()

order_status
delivered    96478
Name: count, dtype: int64

In [119]:
orders.shape

(96478, 8)

**# Merge Customers and Orders**

In [120]:
customer_orders = pd.merge(
    customers, orders,
    on = 'customer_id',
    how='inner'
)

In [121]:
customer_orders.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:00,16-05-2017 15:22,23-05-2017 10:47,25-05-2017 10:35,05-06-2017 00:00
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:00,12-01-2018 20:58,15-01-2018 17:14,29-01-2018 12:41,06-02-2018 00:00
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:00,20-05-2018 16:19,11-06-2018 14:31,14-06-2018 17:58,13-06-2018 00:00
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:00,13-03-2018 17:29,27-03-2018 23:22,28-03-2018 16:04,10-04-2018 00:00
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:00,29-07-2018 10:10,30-07-2018 15:16,09-08-2018 20:55,15-08-2018 00:00

In [122]:
customer_orders.shape

(96478, 12)

In [123]:
list(customer_orders.columns)

['customer_id',
 'customer_unique_id',
 'customer_zip_code_prefix',
 'customer_city',
 'customer_state',
 'order_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date']

In [124]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [125]:
customer_orders_payments =pd.merge(
    customer_orders,
    payments,
    on='order_id',
    how='inner'
)

In [126]:
customer_orders_payments.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_sequential,payment_type,payment_installments,payment_value
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:00,16-05-2017 15:22,23-05-2017 10:47,25-05-2017 10:35,05-06-2017 00:00,1,credit_card,2,146.87
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:00,12-01-2018 20:58,15-01-2018 17:14,29-01-2018 12:41,06-02-2018 00:00,1,credit_card,8,335.48
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:00,20-05-2018 16:19,11-06-2018 14:31,14-06-2018 17:58,13-06-2018 00:00,1,credit_card,7,157.73
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:00,13-03-2018 17:29,27-03-2018 23:22,28-03-2018 16:04,10-04-2018 00:00,1,credit_card,1,173.30
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:00,29-07-2018 10:10,30-07-2018 15:16,09-08-2018 20:55,15-08-2018 00:00,1,credit_card,8,252.25

In [127]:
customer_orders_payments.shape

(100756, 16)

In [128]:
payment_summary = (
    payments.groupby('order_id', as_index=False)
    ['payment_value'].sum()
)

In [129]:
payment_summary.head()

                           order_id  payment_value
0  00010242fe8c5a6d1ba2dd792cb16214          72.19
1  00018f77f2f0320c557190d7a144bdd3         259.83
2  000229ec398224ef6ca0657da4fc703e         216.87
3  00024acbcdf0a6daa1e931b038114c75          25.78
4  00042b26cf59d7ce69dfabb4e55b4fd9         218.04

In [130]:
payment_summary['order_id'].nunique()

99440

In [131]:
len(payment_summary)

99440

In [132]:
payment_summary.shape

(99440, 2)

In [133]:
rfm_base=pd.merge(
    customer_orders,
    payment_summary,
    on='order_id',
    how='inner'
)

In [134]:
rfm_base.shape

(96477, 13)

In [135]:
rfm_base.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_value
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:00,16-05-2017 15:22,23-05-2017 10:47,25-05-2017 10:35,05-06-2017 00:00,146.87
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:00,12-01-2018 20:58,15-01-2018 17:14,29-01-2018 12:41,06-02-2018 00:00,335.48
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:00,20-05-2018 16:19,11-06-2018 14:31,14-06-2018 17:58,13-06-2018 00:00,157.73
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:00,13-03-2018 17:29,27-03-2018 23:22,28-03-2018 16:04,10-04-2018 00:00,173.30
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:00,29-07-2018 10:10,30-07-2018 15:16,09-08-2018 20:55,15-08-2018 00:00,252.25

In [136]:
rfm_base[
    [
        'customer_unique_id',
        'order_id',
        'order_purchase_timestamp',
        'payment_value'
    ]
].head()

,customer_unique_id,order_id,order_purchase_timestamp,payment_value
0,861eff4711a542e4b93843c6dd7febb0,00e7ee1b050b8499577073aeb2a297a1,2017-05-16 15:05:00,146.87
1,290c77bc529b7ac935b93aa66c333dc3,29150127e6685892b6eab3eec79f59c7,2018-01-12 20:48:00,335.48
2,060e732b5b29e8181a18229c7b0b2b5e,b2059ed67ce144a36e2aa97d2c9e9ad2,2018-05-19 16:07:00,157.73
3,259dac757896d24d7702b9acbbff3f3c,951670f92359f4fe4a63112aa7306eba,2018-03-13 16:06:00,173.30
4,345ecd01c38d18a9036ed96c73b8d066,6b7d50bd145f6fc7f33cebabd7e49d0f,2018-07-29 09:51:00,252.25

In [137]:
#For Recency

snapshot_date =rfm_base['order_purchase_timestamp'].max()
print(snapshot_date)

2018-08-29 15:00:00

In [138]:
rfm =rfm_base.groupby('customer_unique_id').agg({
    'order_purchase_timestamp': 'max',
    'order_id':'nunique',
    'payment_value':'sum'
}).reset_index()

In [139]:
rfm.head()

,customer_unique_id,order_purchase_timestamp,order_id,payment_value
0,0000366f3b9a7992bf8c76cfdf3221e2,2018-05-10 10:56:00,1,141.90
1,0000b849f77a49e4a4ce2b2a4ca5be3f,2018-05-07 11:11:00,1,27.19
2,0000f46a3911fa3c0805444483337064,2017-03-10 21:05:00,1,86.22
3,0000f6ccb0745a6a4b88665a16c9f078,2017-10-12 20:29:00,1,43.62
4,0004aac84e0df4da2b147fca70cf8255,2017-11-14 19:45:00,1,196.89

In [140]:
rfm.columns = [
    'customer_unique_id',
    'last_purchase_date',
    'frequency',
    'monetary'
]

In [141]:
rfm.head()

                 customer_unique_id  last_purchase_date  frequency  monetary
0  0000366f3b9a7992bf8c76cfdf3221e2 2018-05-10 10:56:00          1    141.90
1  0000b849f77a49e4a4ce2b2a4ca5be3f 2018-05-07 11:11:00          1     27.19
2  0000f46a3911fa3c0805444483337064 2017-03-10 21:05:00          1     86.22
3  0000f6ccb0745a6a4b88665a16c9f078 2017-10-12 20:29:00          1     43.62
4  0004aac84e0df4da2b147fca70cf8255 2017-11-14 19:45:00          1    196.89

In [142]:
rfm.shape

(93357, 4)

In [143]:
rfm['recency']=(
    snapshot_date-rfm['last_purchase_date']

).dt.days

In [144]:
rfm.head()

,customer_unique_id,last_purchase_date,frequency,monetary,recency
0,0000366f3b9a7992bf8c76cfdf3221e2,2018-05-10 10:56:00,1,141.90,111
1,0000b849f77a49e4a4ce2b2a4ca5be3f,2018-05-07 11:11:00,1,27.19,114
2,0000f46a3911fa3c0805444483337064,2017-03-10 21:05:00,1,86.22,536
3,0000f6ccb0745a6a4b88665a16c9f078,2017-10-12 20:29:00,1,43.62,320
4,0004aac84e0df4da2b147fca70cf8255,2017-11-14 19:45:00,1,196.89,287

In [145]:
rfm[['recency','frequency','monetary']].describe()

            recency     frequency      monetary
count  93357.000000  93357.000000  93357.000000
mean     236.937155      1.033420    165.198772
std      152.584344      0.209099    226.314579
min        0.000000      1.000000      9.590000
25%      113.000000      1.000000     63.060000
50%      218.000000      1.000000    107.780000
75%      345.000000      1.000000    182.560000
max      694.000000     15.000000  13664.080000

In [146]:
rfm['R_score'] = pd.qcut(
    rfm['recency'],
    q=5,
    labels=[5,4,3,2,1]
)

In [147]:
rfm['R_score'].value_counts()

R_score
5    18728
3    18709
4    18705
1    18638
2    18577
Name: count, dtype: int64

In [148]:
rfm['frequency'].value_counts().head(20)

frequency
1     90556
2      2573
3       181
4        28
5         9
6         5
7         3
9         1
15        1
Name: count, dtype: int64

In [149]:
def frequency_score(x):
    if x >= 3:
        return 5
    elif x == 2:
        return 4
    else:
        return 1

rfm['F_score'] = rfm['frequency'].apply(frequency_score)

In [150]:
rfm['F_score'].value_counts()

F_score
1    90556
4     2573
5      228
Name: count, dtype: int64

In [151]:
rfm['frequency'].describe()

count    93357.000000
mean         1.033420
std          0.209099
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         15.000000
Name: frequency, dtype: float64

In [152]:
#rename
def frequency_score(x):
    if x == 1:
        return "One-Time Buyer"
    elif x == 2:
        return "Returning Customer"
    else:
        return "Loyal Customer"

rfm['frequency_segment'] = rfm['frequency'].apply(frequency_score)

In [153]:
rfm['frequency_segment'].value_counts()

frequency_segment
One-Time Buyer        90556
Returning Customer     2573
Loyal Customer          228
Name: count, dtype: int64

In [154]:
rfm['M_score'] = pd.qcut(
    rfm['monetary'],
    q=5,
    labels=[1,2,3,4,5]
)

In [155]:
rfm['M_score'].value_counts()

M_score
2    18683
4    18675
1    18673
5    18668
3    18658
Name: count, dtype: int64

In [156]:
rfm['M_score'].value_counts()

M_score
2    18683
4    18675
1    18673
5    18668
3    18658
Name: count, dtype: int64

In [157]:
#for frequency
rfm['F_score'] = np.where(
    rfm['frequency'] == 1,
    1,
    5
)

In [158]:
rfm['frequency_segment'].value_counts()

frequency_segment
One-Time Buyer        90556
Returning Customer     2573
Loyal Customer          228
Name: count, dtype: int64

In [159]:
#check
(rfm['frequency'] > 1).sum()

np.int64(2801)

In [160]:
# Repeat Purchase Rate

((rfm['frequency'] > 1).sum() / len(rfm) * 100)

np.float64(3.0003106355174225)

In [161]:
rfm['RM_score'] = (
    rfm['R_score'].astype(str) +
    rfm['M_score'].astype(str)
)

In [162]:
rfm[['recency','monetary']].describe()

            recency      monetary
count  93357.000000  93357.000000
mean     236.937155    165.198772
std      152.584344    226.314579
min        0.000000      9.590000
25%      113.000000     63.060000
50%      218.000000    107.780000
75%      345.000000    182.560000
max      694.000000  13664.080000

In [163]:
#Combined View
rfm[['R_score','M_score']].head()

  R_score M_score
0       4       4
1       4       1
2       1       2
3       2       1
4       2       4

In [164]:
rfm.groupby('frequency_segment').agg({
    'monetary':'mean',
    'recency':'mean'
}).round(2)

                    monetary  recency
frequency_segment
Loyal Customer        506.79   201.28
One-Time Buyer        160.76   237.48
Returning Customer    291.03   220.89

In [165]:
# Best Customers
rfm[
    (rfm['R_score'] == 5) &
    (rfm['M_score'] == 5)
].shape

(3815, 10)

In [166]:
#Worst Customers
rfm[
    (rfm['R_score'] == 1) &
    (rfm['M_score'] == 1)
].shape

(3888, 10)

In [167]:
#heatmap matrix
rfm.groupby(['R_score','M_score']).size().unstack(fill_value=0)

/tmp/ipykernel_1977/2223196038.py:2: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

M_score     1     2     3     4     5
R_score
5        3714  3543  3765  3891  3815
4        3618  3545  3812  3904  3826
3        3905  3652  3733  3857  3562
2        3548  4001  3653  3621  3754
1        3888  3942  3695  3402  3711

In [168]:
#final customer segment column.
def segment_customer(row):

    if row['R_score'] >= 4 and row['M_score'] >= 4:
        return 'Champion'

    elif row['R_score'] >= 4 and row['M_score'] <= 3:
        return 'Potential Loyalist'

    elif row['R_score'] <= 2 and row['M_score'] >= 4:
        return 'At Risk'

    elif row['R_score'] <= 2 and row['M_score'] <= 2:
        return 'Lost Customer'

    else:
        return 'Regular Customer'

In [169]:
rfm['customer_segment'] = rfm.apply(
    segment_customer,
    axis=1
)

In [170]:
rfm['customer_segment'].value_counts()

customer_segment
Regular Customer      26057
Potential Loyalist    21997
Champion              15436
Lost Customer         15379
At Risk               14488
Name: count, dtype: int64

In [171]:
pd.crosstab(
    rfm['customer_segment'],
    rfm['frequency_segment']
)

frequency_segment   Loyal Customer  One-Time Buyer  Returning Customer
customer_segment
At Risk                         60           13739                 689
Champion                       117           14446                 873
Lost Customer                    3           15298                  78
Potential Loyalist               5           21778                 214
Regular Customer                43           25295                 719

In [172]:
rfm.to_csv('rfm_customer_segments.csv', index=False)

# Visualization

In [173]:
import plotly.express as px

In [174]:
#1. Customer Value Segmentation
segment_counts = (
    rfm['customer_segment']
    .value_counts()
    .reset_index()
)

segment_counts.columns = ['Segment', 'Customers']

fig = px.bar(
    segment_counts,
    x='Customers',
    y='Segment',
    orientation='h',
    color='Segment',
    title='Customer Value Segmentation',
    color_discrete_sequence=px.colors.qualitative.Bold
)

fig.update_traces(
    marker_line_color='black',
    marker_line_width=1
)

fig.update_layout(
    title_x=0.5,
    plot_bgcolor='white',
    paper_bgcolor='white',
    xaxis_title='Number of Customers',
    yaxis_title='',
    showlegend=False
)

fig.show()

In [175]:
# 2. RFM Heatmap


heatmap = (
    rfm.groupby(['R_score', 'M_score'])
       .size()
       .reset_index(name='Customers')
)

fig = px.density_heatmap(
    heatmap,
    x='M_score',
    y='R_score',
    z='Customers',
    text_auto=True,
    color_continuous_scale='RdYlGn',
    title='RFM Customer Distribution Heatmap'
)

fig.update_layout(
    title_x=0.5,
    plot_bgcolor='white',
    paper_bgcolor='white',
    xaxis_title='Monetary Score',
    yaxis_title='Recency Score'
)

fig.show()

/tmp/ipykernel_1977/1453538711.py:5: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [176]:
# 3: Average Spend by Customer Segment
avg_spend = (
    rfm.groupby('customer_segment')['monetary']
       .mean()
       .sort_values(ascending=False)
       .reset_index()
)

fig = px.bar(
    avg_spend,
    x='customer_segment',
    y='monetary',
    color='customer_segment',
    title='Average Spend by Customer Segment',
    color_discrete_sequence=px.colors.qualitative.Set2
)

fig.update_traces(
    marker_line_color='black',
    marker_line_width=1
)

fig.update_layout(
    title_x=0.5,
    plot_bgcolor='white',
    paper_bgcolor='white',
    xaxis_title='Customer Segment',
    yaxis_title='Average Spend',
    showlegend=False
)

fig.show()

In [177]:
#4: Frequency Segment Distribution
retention_counts = (
    rfm['frequency_segment']
    .value_counts()
    .reset_index()
)

retention_counts.columns = ['Segment', 'Customers']

fig = px.bar(
    retention_counts,
    x='Segment',
    y='Customers',
    color='Segment',
    title='Frequency Segment Distribution',
    color_discrete_map={
        'One-Time Buyer': '#E63946',
        'Returning Customer': '#457B9D',
        'Loyal Customer': '#2A9D8F'
    }
)

fig.update_traces(
    marker_line_color='black',
    marker_line_width=1
)

fig.update_layout(
    title_x=0.5,
    plot_bgcolor='white',
    paper_bgcolor='white',
    yaxis_title='Number of Customers',
    showlegend=False
)

fig.show()

In [178]:
#5. Customer Segment vs Retention Segment
cross_tab = pd.crosstab(
    rfm['customer_segment'],
    rfm['frequency_segment']
)

fig = px.imshow(
    cross_tab,
    text_auto=True,
    color_continuous_scale='Blues',
    aspect='auto',
    title='Customer Value Segment vs Retention Segment'
)

fig.update_layout(
    title_x=0.5,
    plot_bgcolor='white',
    paper_bgcolor='white'
)

fig.show()